Repository sabeq96/Eventerio, pull requests merged in 2019-05, with the labels that each got.

#28 fix: Fixed Firebase updateUser method.
  utils/firebase.js
Labels: Fix

#29 Event Card view in Home
  .firebase/hosting.YnVpbGQ.cache
  .gitignore
  components/Grid/index.js
  components/Nav/index.js
  components/Pages/SingleEvent/index.js
  containers/Home/index.js
  index.js
  style.css
  utils/firebase.js
Labels: Ready to Merge

#34 fix: header components in seperate directory
  components/HeaderAppBar/index.js
  containers/Header/AppBar.js
  containers/Header/LeftSection.js
  containers/Header/RightSection.js
  containers/Header/index.js
Labels: Ready to Merge

#35 feature/account settings
  components/Nav/index.js
  components/Pages/AccountSettings/AvatarSection.js
  components/Pages/AccountSettings/index.js
  index.js
  utils/firebase.js
Labels: Feature, Ready to Merge

#40 feature: handle change password
  components/Login/ContentTypes.js
  components/Login/index.js
  utils/firebase.js
Labels: Ready to Merge

#37 fix: account settings save user data with avatar
  components/Pages/AccountSettings/index.js
  utils/firebase.js
Labels: Fix, Ready to Merge

#44 fix: event details as container
  .firebase/hosting.YnVpbGQ.cache
  components/Nav/index.js
  components/Pages/SingleEvent/index.js
  constants/errorMessages.js
  containers/SingleEvent/index.js
  index.js
  utils/firebase.js
Labels: Fix, Ready to Merge

#45 fix: account settings as container
  components/Pages/AccountSettings/index.js
  containers/AccountSettings/index.js
  index.js
Labels: Fix, Ready to Merge

#38 Add mod event
  .firebase/hosting.YnVpbGQ.cache
  components/DatePicker/index.js
  components/DatePicker/themes/airbnb.css
  components/DatePicker/themes/confetti.css
  components/DatePicker/themes/dark.css
  components/DatePicker/themes/light.css
  components/DatePicker/themes/material_blue.css
  components/DatePicker/themes/material_green.css
  components/DatePicker/themes/material_orange.css
  components/DatePicker/themes/material_red.css
  components/Nav/index.js
  components/Pages/AddModEvent/index.js
  containers/AddModEvent/index.js
  containers/Header/AppBar.js
  containers/SingleEvent/index.js
  index.js
  package-lock.json
  package.json
  style.css
  utils/firebase.js
Labels: Feature, Ready to Merge

#48 feature: config
  config/index.js.dist
Labels: Feature, Ready to Merge

#47 feature: geolocation util
  package-lock.json
  package.json
  utils/geolocation.js
Labels: Feature, Ready to Merge

#46 feature: google map component
  .gitignore
  components/GoogleMap/index.js
  components/Pages/SingleEvent/index.js
  containers/SingleEvent/index.js
Labels: Feature, Ready to Merge

#64 feature: get user location
  utils/geolocation.js
Labels: Feature, Ready to Merge

#66 feature: new app logo
  assets/Logo/EVENTERIO_LOGO.svg
  assets/favicon.ico
  assets/icon.png
  assets/icon192.png
  containers/Header/LeftSection.js
Labels: Feature, Ready to Merge

#36 Event List view (#15)
  components/Nav/index.js
  components/Pages/EventList/index.js
  index.js
  style.css
Labels: Feature, Ready to Merge

#69 Feature/get events in area
  utils/eventsHelper.js
  utils/firebase.js
  utils/geolocation.js
Labels: Feature, Ready to Merge

#73 fix: changed emails' inputs type to email
  components/Login/ContentTypes.js
Labels: Fix, Ready to Merge

#72 fix: changed app name
  manifest.template.json
  package.json
Labels: Fix, Ready to Merge

#80 Feat/app styles
  assets/bg/navbar-bg.jpg
  style.css
Labels: Feature, Ready to Merge
