Repository sabeq96/Eventerio, pull requests merged in 2019-06, with the labels that each got.

#86 Feat/readme
  README.md
  showup/1_eventerio.jpg
  showup/2_eventerio.jpg
  showup/3_eventerio.jpg
  showup/4_eventerio.jpg
  showup/5_eventerio.jpg
Labels: Feature, Ready to Merge

#82 fix: Delete comments from singe event
  components/Pages/SingleEvent/index.js
  containers/AddModEvent/index.js
  containers/SingleEvent/index.js
Labels: Fix, Ready to Merge

#83 feature: action result modal
  components/ActionResultModal/actionResultTypes.js
  components/ActionResultModal/index.js
  containers/Header/index.js
  package-lock.json
  utils/store.js
Labels: Feature, Ready to Merge

#74 feature: get events in user area
  containers/AccountSettings/index.js
  containers/EventList/index.js
  utils/firebase.js
Labels: Feature, IMPORTANT, Ready to Merge

#68 fix: event card extras
  components/Pages/SingleEvent/index.js
  containers/SingleEvent/index.js
  utils/eventsHelper.js
  utils/firebase.js
Labels: Fix, IMPORTANT, Ready to Merge

#87 fix/auth user
  .firebase/hosting.YnVpbGQ.cache
  components/Nav/index.js
  components/Pages/EventList/index.js
  containers/AccountSettings/index.js
  containers/AddModEvent/index.js
  containers/EventList/index.js
  containers/SingleEvent/index.js
  index.js
  utils/eventsHelper.js
  utils/firebase.js
Labels: Fix, IMPORTANT, Ready to Merge

#85 WIP: feature: reset password
  components/Login/ContentTypes.js
  components/Login/index.js
  utils/firebase.js
Labels: Feature, Ready to Merge

#102 fix: Added map component to add/edit event views
  components/Pages/AddModEvent/index.js
  containers/AddModEvent/index.js
  utils/firebase.js
Labels: Fix, Ready to Merge
